version: "3.8"

services:
  neo4j:
    build: ./neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/your_password"  # 设置 Neo4j 登录密码
      NEO4J_apoc_export_file_enabled: "true"  # 启用 APOC 文件导出功能
      NEO4J_apoc_import_file_enabled: "true"  # 启用 APOC 文件导入功能
      NEO4J_apoc_import_file_use__neo4j__config: "true"  # 使用 Neo4j 配置路径
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"  # 启用 APOC 所有功能
      NEO4J_PLUGINS: '["graph-data-science"]'  # 加载 GDS 插件
    volumes:
      - mydata:/data  # 数据存储卷


volumes:
  mydata:
